### ISSUE TITLE
Query .container class width default

### ISSUE THREAD

**Issue by kool-kat** [howardmann/simple_css_library#1]
Hi Howard,

Like your code but query why you set the outer **.container** wrapper to 85% width.

Was there a coding reason? Or can I default it to 100% to use max available space in my page.

Also food for thought, may want to choose a better class namespace or add a prefix as some class names are to obvious (eg container, col, row) and likely to clash with others a site may already use.

Cheers

**Comment by howardmann** [comment]
Hey kool-kat,

Wow didn't realise anyone was watching this repo, I haven't touched it in ages. 

No particular reason for 85%, only for aesthetic purposes when you load on a large desktop monitor doesn't look good taking up the whole screen.

Re: class namespace, it is typically convention to use container, col and row for CSS frameworks. The idea is for this to replace any existing grid system, you shouldn't have more than one otherwise its chaos. It's meant to be lightweight so feel free to fork and amend.

I gained inspiration from simple grid which I took some elements from. Always good education to build a bare bones CSS framework that works for you
http://www.simplegrid.io/

**Comment by kool-kat** [comment]
Thanks for clarifying.

RE:Namespace suggestion

I wasn't querying your reasoning behind using obvious and logical class naming... rather the likelihood it may already exist and conflict with class definitions already in use and applied by website plugins etc

Easy to change, so I will do locally.
